### ISSUE TITLE
Needed to modify Win10 PowerShell Execution Policy before execution

### ISSUE THREAD

**Issue by brford** [Sneakysecdoggo/Wynis#2]
In order to run Wynis I needed to modify Windows 10 Powershell Execution properties. See:

 https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-7.1 

I modified the 'Bypass' policy to allow for Current User.  Did this and Wynis ran perfectly writing all data to a created subdirectory local to the source.  Good results.

**Comment by yaslam-dev** [comment]
It happened to me as well, I added 'Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope CurrentUser ' as the first line of the script and everything worked perfect for me.

**Comment by Sneakysecdoggo** [comment]
Add prerequisites with theses informations
