### ISSUE TITLE
SeCreatePermanentPrivilege label and SeCreateGlobalPrivilege value

### ISSUE THREAD

**Issue by Nioubi24** [Sneakysecdoggo/Wynis#4]
Hi,

In WynisWIN10-CISv1.0.ps1 code : 
- Line 809, user's right named "SeCreateGlobalPrivilege" is searched in $seceditfile
- but Line 811, user's right label assigned to this result is "SeCreatePermanentPrivilege"... another user's right

==> the value of  "SeCreateGlobalPrivilege" parameter is labeled as "SeCreatePermanentPrivilege" value... ;-(

```PowerShell
#Create permanent shared objects'

$indextest += 1
$chaine = $null
$traitement = $null
$id = "URA" + "$indextest"
$chaine = "$id" + ";" + "(L1)Ensure Create permanent shared objects, No one,value must empty" + ";"
$chaineSID = Get-Content $seceditfile |Select-String "SeCreateGlobalPrivilege" 
$chaineSID = $chaineSID.line
$traitement = "SeCreatePermanentPrivilege" + ":"
$traitement += Reverse-SID $chaineSID

$chaine += $traitement
$chaine>> $nomfichier
```

Same issue in code : 
- WynisWIN2016-CISv1.0.ps1, lines 806 and 808
- WynisWIN2016DC-CISv1.0.ps1, lines 846 and 848

Regards

**Comment by Sneakysecdoggo** [comment]
Hello,
Thank you, it is fixed on version 1.1
