### ISSUE TITLE
LocalAccountTokenFilterPolicy

### ISSUE THREAD

**Issue by Nioubi24** [Sneakysecdoggo/Wynis#5]
Hi,

According to Microsoft [https://docs.microsoft.com/en-us/troubleshoot/windows-server/windows-security/user-account-control-and-remote-restriction](url) and AdmxHelp [https://admx.help/?Category=SecurityBaseline&Policy=Microsoft.Policies.PtH::Pol_PtH_LATFP](url) the value of the 'LocalAccountTokenFilterPolicy' property is : 

- Enabled : 0
- Disabled : 1

And the recommended value is 'Enabled', so the script should verify the Register value is set to 0, not 1.

WynisWIN10-CISc1.1.PS1, line 4416

```PowerShell
$id = "MSSG" + "$indextest"
$chaine = "$id" + ";" + "(L1)Ensure 'Apply UAC restrictions to local accounts on network logons' is set to 'Enabled', value must be 1" + ";"
$exist = Test-Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System"
if ( $exist -eq $true) {
 $traitement = Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System"|Select-Object LocalAccountTokenFilterPolicy
 $traitement = $traitement.LocalAccountTokenFilterPolicy
}
else {
 $traitement = "not configure"
}
```
Same issue in WS2016's script, around Line Number 3479.

Regards

**Comment by Sneakysecdoggo** [comment]
Hello,
Thank you, it is fixed on version 1.1
