### ISSUE TITLE
NoNameReleaseOnDemand

### ISSUE THREAD

**Issue by Nioubi24** [Sneakysecdoggo/Wynis#6]
Hi,

According to AdmxHelp [https://admx.help/?Category=SecurityBaseline&Policy=Microsoft.Policies.MSS::Pol_MSS_NoNameReleaseOnDemand](url) the value of the 'NoNameReleaseOnDemand' should be :

    Enabled : 1
    Disabled : 0

And the recommended value is 'Enabled', so the script shouldn't indicate "the value must be 300000" (bad Copy/Paste from the previous lines...?).

WynisWIN10-CISc1.1.PS1, line 4663
```PowerShell
#MSS: (NoNameReleaseOnDemand) Allow the computer to ignore NetBIOS name release requests except from WINS servers
$indextest += 1
$chaine = $null
$traitement = $null
$exist = $null
$id = "MSSL" + "$indextest"
$chaine = "$id" + ";" + "(L1)Ensure 'MSS: (NoNameReleaseOnDemand) Allow the computer to ignore NetBIOS name release requests except from WINS servers' is set to 'Enabled, value must be 300000" + ";"
$exist = Test-Path "HKLM:\SYSTEM\CurrentControlSet\Services\NetBT\\Parameters"
if ( $exist -eq $true) {
 $traitement = Get-ItemProperty "HKLM:\SYSTEM\CurrentControlSet\Services\NetBT\Parameters" |Select-Object NoNameReleaseOnDemand
 $traitement = $traitement.NoNameReleaseOnDemand
}
else {
 $traitement = "not configure"
}
```
Same issue in WS2016 script around line 3700.

Regards

**Comment by Sneakysecdoggo** [comment]
Hello,
Thank you, it is fixed on version 1.1
